-- MySQL Script generated by MySQL Workbench
-- Sun Aug  4 17:00:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock` ;

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`users` ;

CREATE TABLE IF NOT EXISTS `stock`.`users` (
  `id_user` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` BIGINT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `level` TINYINT(1) UNSIGNED NULL DEFAULT 4,
  `nom_complet` VARCHAR(100) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `LOGIN` (`username` ASC, `email` ASC, `phone` ASC));


-- -----------------------------------------------------
-- Table `stock`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`sites` ;

CREATE TABLE IF NOT EXISTS `stock`.`sites` (
  `id_site` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_site` VARCHAR(50) NOT NULL,
  `details` VARCHAR(255) NULL,
  `superviseur` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_site`),
  INDEX `NOMSITE` (`nom_site` ASC, `id_site` ASC),
  INDEX `fk_sites_users_idx` (`superviseur` ASC),
  CONSTRAINT `fk_sites_users`
    FOREIGN KEY (`superviseur`)
    REFERENCES `stock`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`articles` ;

CREATE TABLE IF NOT EXISTS `stock`.`articles` (
  `id_article` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `fournisseur` VARCHAR(50) NOT NULL,
  `qte` BIGINT UNSIGNED ZEROFILL  NOT NULL,
  `qte_min` INT ZEROFILL NOT NULL,
  `date_creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_article`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `FOURNISSEURS` (`fournisseur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`articles_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`articles_site` ;

CREATE TABLE IF NOT EXISTS `stock`.`articles_site` (
  `id_articles_site` INT NOT NULL AUTO_INCREMENT,
  `qte_min` INT ZEROFILL NOT NULL,
  `qte` BIGINT ZEROFILL NOT NULL,
  `date_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_article` BIGINT NOT NULL,
  `id_site` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_articles_site`),
  INDEX `fk_articles_site_articles1_idx` (`id_article` ASC),
  INDEX `fk_articles_site_sites1_idx` (`id_site` ASC),
  CONSTRAINT `fk_articles_site_articles1`
    FOREIGN KEY (`id_article`)
    REFERENCES `stock`.`articles` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_site_sites1`
    FOREIGN KEY (`id_site`)
    REFERENCES `stock`.`sites` (`id_site`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`transfert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`transfert` ;

CREATE TABLE IF NOT EXISTS `stock`.`transfert` (
  `id_transfert` BIGINT NOT NULL AUTO_INCREMENT,
  `id_article` BIGINT NOT NULL,
  `id_site` INT NOT NULL,
  `qte_envoyer` INT NOT NULL,
  `date_envoi` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) ZEROFILL NULL,
  `id_demandeur` BIGINT NOT NULL,
  `id_sender` BIGINT NOT NULL,
  `date_reception` DATETIME NULL,
  `details` VARCHAR(255) NULL,
  PRIMARY KEY (`id_transfert`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`sortis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`sortis` ;

CREATE TABLE IF NOT EXISTS `stock`.`sortis` (
  `id_sorti` BIGINT NOT NULL AUTO_INCREMENT,
  `qte` INT NOT NULL,
  `date_sortie` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nom_client` VARCHAR(50) NULL,
  `ijd` VARCHAR(20) NOT NULL,
  `id_articles_site` INT NOT NULL,
  PRIMARY KEY (`id_sorti`),
  INDEX `fk_sortis_articles_site1_idx` (`id_articles_site` ASC),
  CONSTRAINT `fk_sortis_articles_site1`
    FOREIGN KEY (`id_articles_site`)
    REFERENCES `stock`.`articles_site` (`id_articles_site`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`notifications` ;

CREATE TABLE IF NOT EXISTS `stock`.`notifications` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `statut` TINYINT(1) ZEROFILL NULL,
  `titre` VARCHAR(45) NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  `date_notif` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_notification`),
  INDEX `fk_notifications_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `stock`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
