<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Articles_site_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get articles_site by id_articles_site
     */
    function get_articles_site($id_articles_site)
    {
        return $this->db->get_where('articles_site',array('id_articles_site'=>$id_articles_site))->row_array();
    }
        
    /*
     * Get all articles_sites
     */
    function get_all_articles_sites()
    {
        $this->db->order_by('id_articles_site', 'desc');
        return $this->db->get('articles_site')->result_array();
    }
        
    /*
     * function to add new articles_site
     */
    function add_articles_site($params)
    {
        $this->db->insert('articles_site',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update articles_site
     */
    function update_articles_site($id_articles_site,$params)
    {
        $this->db->where('id_articles_site',$id_articles_site);
        return $this->db->update('articles_site',$params);
    }
    
    /*
     * function to delete articles_site
     */
    function delete_articles_site($id_articles_site)
    {
        return $this->db->delete('articles_site',array('id_articles_site'=>$id_articles_site));
    }
}
